name: Build Labubu from ZIP and produce installer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find ZIP file
        run: |
          if (Test-Path -Path ./game_files.zip) {
            Write-Host "Found game_files.zip at repository root."
          } else {
            $z = Get-ChildItem -Path . -Filter *.zip -Recurse | Select-Object -First 1
            if ($null -eq $z) { Write-Error "No ZIP file found in repository root or subfolders."; exit 1 }
            Write-Host "Found ZIP: $($z.FullName)"
          }

      - name: Extract game ZIP (to ./game)
        run: |
          if (Test-Path -Path ./game_files.zip) {
            Expand-Archive -Path ./game_files.zip -DestinationPath ./game -Force
          } else {
            $z = Get-ChildItem -Path . -Filter *.zip -Recurse | Select-Object -First 1
            Expand-Archive -Path $z.FullName -DestinationPath ./game -Force
          }

      - name: Show extracted files
        run: dir ./game

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (if package.json exists)
        run: |
          if (Test-Path -Path ./game/package.json) {
            cd game
            npm ci
            cd ..
          } else {
            Write-Host "No package.json found under ./game — skipping npm ci"
          }

      - name: Build (electron-builder) if configured
        run: |
          if (Test-Path -Path ./game/package.json) {
            cd game
            npm run dist || (Write-Host "npm run dist failed or not defined"; exit 1)
          } else {
            Write-Host "No package.json -> cannot run build. Ensure the ZIP contains a Node/Electron project."
            exit 1
          }

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: labubu-installer
          path: ./game/dist/*.exe
